flat_bias_correction_triad.Rmd:
  path: dev/flat_bias_correction_triad.Rmd
  state: active
  R:
  - R/apply_time_space_weight.R
  - R/apply_triad_weight.R
  - R/bias_correction_triad.R
  - R/compute_interval_probability.R
  - R/compute_time_space_weight.R
  - R/compute_triad_probability.R
  - R/compute_triad_probability_old.R
  - R/compute_triad_weight.R
  - R/mutate_triad_occurence_per_song.R
  tests:
  - tests/testthat/test-compute_interval_probability.R
  - tests/testthat/test-compute_triad_probability_old.R
  - tests/testthat/test-compute_triad_probability.R
  - tests/testthat/test-mutate_triad_occurence_per_song.R
  - tests/testthat/test-compute_triad_weight.R
  - tests/testthat/test-apply_triad_weight.R
  - tests/testthat/test-compute_time_space_weight.R
  - tests/testthat/test-apply_time_space_weight.R
  - tests/testthat/test-bias_correction_triad.R
  vignettes: vignettes/bias-correction.Rmd
  inflate:
    flat_file: dev/flat_bias_correction_triad.Rmd
    vignette_name: Bias Correction
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_compute_population_estimates.Rmd:
  path: dev/flat_compute_population_estimates.Rmd
  state: active
  R:
  - R/compute_population_estimates.R
  - R/estimate_population_by_country_year.R
  tests:
  - tests/testthat/test-estimate_population_by_country_year.R
  - tests/testthat/test-compute_population_estimates.R
  vignettes: vignettes/population-estimates.Rmd
  inflate:
    flat_file: dev/flat_compute_population_estimates.Rmd
    vignette_name: Population Estimates
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_config.Rmd:
  path: dev/flat_config.Rmd
  state: active
  R:
  - R/get_config.R
  - R/get_playlist_id.R
  tests:
  - tests/testthat/test-get_config.R
  - tests/testthat/test-get_playlist_id.R
  vignettes: vignettes/manage-config.Rmd
  inflate:
    flat_file: dev/flat_config.Rmd
    vignette_name: Manage config
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_get_spotify_api_playlist.Rmd:
  path: dev/flat_get_spotify_api_playlist.Rmd
  state: active
  R:
  - R/auth_spotify.R
  - R/get_spotify_api_playlist.R
  - R/get_spotify_api_triad_playlists.R
  tests:
  - tests/testthat/test-auth_spotify.R
  - tests/testthat/test-get_spotify_api_playlist.R
  - tests/testthat/test-get_spotify_api_triad_playlists.R
  vignettes: vignettes/get-from-spotify.Rmd
  inflate:
    flat_file: dev/flat_get_spotify_api_playlist.Rmd
    vignette_name: Get from spotify
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_insert_line_breaks_adaptive.Rmd:
  path: dev/flat_insert_line_breaks_adaptive.Rmd
  state: active
  R: R/insert_line_breaks_adaptive.R
  tests: tests/testthat/test-insert_line_breaks_adaptive.R
  vignettes: vignettes/insert-line-breaks.Rmd
  inflate:
    flat_file: dev/flat_insert_line_breaks_adaptive.Rmd
    vignette_name: Insert Line Breaks
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_parse_triade.Rmd:
  path: dev/flat_parse_triade.Rmd
  state: active
  R:
  - R/clean_song_title.R
  - R/parse_triade.R
  tests:
  - tests/testthat/test-clean_song_title.R
  - tests/testthat/test-parse_triade.R
  vignettes: vignettes/parse_triade.Rmd
  inflate:
    flat_file: dev/flat_parse_triade.Rmd
    vignette_name: parse_triade
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_plot_tvc_histogram.Rmd:
  path: dev/flat_plot_tvc_histogram.Rmd
  state: active
  R: R/plot_tvc_histogram.R
  tests: tests/testthat/test-plot_tvc_histogram.R
  vignettes: vignettes/plot_tvc_histogram.Rmd
  inflate:
    flat_file: dev/flat_plot_tvc_histogram.Rmd
    vignette_name: plot_tvc_histogram
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_plot_tvc_network.Rmd:
  path: dev/flat_plot_tvc_network.Rmd
  state: active
  R: R/plot_tvc_network.R
  tests: tests/testthat/test-plot_tvc_network.R
  vignettes: vignettes/plot_tvc_network.Rmd
  inflate:
    flat_file: dev/flat_plot_tvc_network.Rmd
    vignette_name: plot_tvc_network
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_plot_tvc_world.Rmd:
  path: dev/flat_plot_tvc_world.Rmd
  state: active
  R:
  - R/group_countries.R
  - R/plot_tvc_world.R
  tests:
  - tests/testthat/test-group_countries.R
  - tests/testthat/test-plot_tvc_world.R
  vignettes: vignettes/triad-world-map.Rmd
  inflate:
    flat_file: dev/flat_plot_tvc_world.Rmd
    vignette_name: Triad World Map
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_read_sheet_triad.Rmd:
  path: dev/flat_read_sheet_triad.Rmd
  state: active
  R: R/read_sheet_triad.R
  tests: tests/testthat/test-read_sheet_triad.R
  vignettes: vignettes/read-googlesheet-triad.Rmd
  inflate:
    flat_file: dev/flat_read_sheet_triad.Rmd
    vignette_name: Read Googlesheet Triad
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_scale_palette_triad.Rmd:
  path: dev/flat_scale_palette_triad.Rmd
  state: active
  R:
  - R/palette_gen_c.R
  - R/palette_gen_d.R
  - R/scale_colour_tvc_c.R
  - R/scale_colour_tvc_d.R
  - R/scale_fill_tvc_c.R
  - R/scale_fill_tvc_d.R
  - R/tvc_corp_palette.R
  tests:
  - tests/testthat/test-tvc_corp_palette.R
  - tests/testthat/test-palette_gen_d.R
  - tests/testthat/test-palette_gen_c.R
  - tests/testthat/test-scale_fill_tvc_c.R
  - tests/testthat/test-scale_colour_tvc_c.R
  - tests/testthat/test-scale_fill_tvc_d.R
  - tests/testthat/test-scale_colour_tvc_d.R
  vignettes: vignettes/custom-colour-palette.Rmd
  inflate:
    flat_file: dev/flat_scale_palette_triad.Rmd
    vignette_name: Custom Colour Palette
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_triad_coverage.Rmd:
  path: dev/flat_triad_coverage.Rmd
  state: active
  R:
  - R/build_triad_from_config.R
  - R/plot_triad_coverage.R
  - R/triad_coverage.R
  tests:
  - tests/testthat/test-build_triad_from_config.R
  - tests/testthat/test-triad_coverage.R
  - tests/testthat/test-plot_triad_coverage.R
  vignettes: vignettes/triad-coverage.Rmd
  inflate:
    flat_file: dev/flat_triad_coverage.Rmd
    vignette_name: Triad Coverage
    open_vignette: true
    check: false
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_write_missing_region.Rmd:
  path: dev/flat_write_missing_region.Rmd
  state: active
  R: R/write_missing_region.R
  tests: tests/testthat/test-write_missing_region.R
  vignettes: vignettes/update-region-google-sheet.Rmd
  inflate:
    flat_file: dev/flat_write_missing_region.Rmd
    vignette_name: Update Region Google Sheet
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_write_missing_triade.Rmd:
  path: dev/flat_write_missing_triade.Rmd
  state: active
  R: R/write_missing_triade.R
  tests: tests/testthat/test-write_missing_triade.R
  vignettes: vignettes/update-triade-google-sheet.Rmd
  inflate:
    flat_file: dev/flat_write_missing_triade.Rmd
    vignette_name: Update Triade Google Sheet
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
keep:
  path: keep
  state: active
  R:
  - R/globals.R
  - R/tvc-package.R
  - R/utils-pipe.R
  tests: []
  vignettes: vignettes/2025-10-28-triade-vanessa-carlton.Rmd
